url: "http://www.goodinternet.org/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "IoGT" # the name of your site, e.g. ACME Corp.

tagline: "Live Better Today"
description: >-
  UNICEF Internet of Good Things website

author: "UNICEF IoGT"

markdown: kramdown

kramdown:
  input: GFM

sass:
  sass_dir: _sass

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page_docs
      sidebar: main_sidebar
  - scope:
      path: "_pages/cms-manual/intro"
      type: "pages"
    values:
      section: "Introduction"
  - scope:
      path: "_pages/cms-manual/content"
      type: "pages"
    values:
      section: "Creating Your Content"
  - scope:
      path: "_pages/cms-manual/comments"
      type: "pages"
    values:
      section: "Commenting"
  - scope:
      path: "_pages/cms-manual/surveys"
      type: "pages"
    values:
      section: "Creating a Survey"

sidebars:
  main_sidebar

exclude:
  - .idea/
  - .git/
  - .vscode/
  - .gitignore
  - .prettierrc
  - CNAME
  - Gemfile
  - Gemfile.lock
